# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fbauthexample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for fbauthexample
	pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Google'
    pod 'FirebaseUI/Facebook'
    pod 'FirebaseUI/Phone'

  target 'fbauthexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fbauthexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
